import localFont from "next/font/local";
import "./globals.css";
import Header from "@/Components/Header";
import {Poppins} from "next/font/google" 
import Footer from "@/Components/Footer";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ["100", "200", "300", '400', "500", '600', '700', '800', '900']
})

export const metadata = {
  title: "Sudais E-Comm.",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
